#!/usr/bin/env ruby
require 'smart_colored/extend'

$LOAD_PATH << "lib"
$LOAD_PATH << "models"

require 'environment'
Environment.environment = ENV["ENVIRONMENT"] || "production"
$stderr = $stdout

require 'person'

def main_menu
<<EOS
What do you want to do? (Enter the number for your choice)
1. Create a Diet Cal.
2. View your Diet Cal.
3. Edit your Diet Cal.
4. Delete your Diet Cal.
EOS
end

def menu_1_select
<<EOS
Select the type of diet (Enter the number for your choice)
1. Vegeterian
2. Vegan
3. Full
EOS
end

def sub_menu_1
<<EOS
How many meals a day? (Enter the number between 3 and 9)
EOS
end

def menu_2_select
<<EOS
Enter your firstname followed by your passcode (Example <Sam 1234>)
EOS
end

def diet_type(i)
  types = ["vegeterian", "Vegan", "Full"]
  types[i-1].capitalize
end

def generate_meal_menu(diet)
  puts sub_menu_1
  diet_num = gets
  return unless diet_num
  diet_num.chomp!
  if diet_num && diet_num.to_i > 2 && diet_num.to_i < 9
    puts "#{diet_num} #{diet_type(diet)} meal diet added."
  else
    puts "'#{diet_num}' is not a valid entry."
    generate_meal_menu(diet)
  end
end

def add_user
  puts "Enter your first name."
  name = gets
  return unless name
  name.chomp!
  person = Person.new(name)
  if person.save
    puts "#{name.capitalize} has been added."
    record_desired_outcomes_for(person)
  else
    puts person.errors
    add_user
  end
end

def generate_create_menu
  puts menu_1_select
  user_select = gets
  return unless user_select
  user_select.chomp!
  if user_select.length < 1 || user_select.to_i < 1 || user_select.to_i > 3
    puts "'#{user_select}' is an incorrect selection! Please enter 1, 2 or 3"
    generate_create_menu
  else
    generate_meal_menu(user_select.to_i)
  end
end

def generate_main_menu
  puts main_menu
  user_input = gets
  return unless user_input
  user_input.chomp!
  if user_input.length < 1 || user_input.to_i < 1 || user_input.to_i > 4
    puts "'#{user_input}' is an incorrect selection! Please enter 1, 2, 3 or 4"
    generate_main_menu
  elsif user_input.to_i == 1
    #add_user
    puts "Enter your first name."
    name = gets
    return unless name
    name.chomp!
    puts "#{name.capitalize} has been added."
    generate_create_menu
  else
    puts menu_2_select
  end
end

puts generate_main_menu
